version: "3.9"

services:
  web:
    image: kishikmaxim/adcm:v0.4.3
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  neo4j_user:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins

    environment:
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=3G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=3G
      - NEO4J_AUTH=neo4j/231099