neo4j:
  #  for neo4j_historical ONLINE:
#  last_url: 'neo4j://127.0.0.1:7688'
  last_url: 'neo4j+s://99c1a702.databases.neo4j.io:7687'
  user: 'neo4j'
  password: '231099'

  #  for neo4j_user Docker container:
  new_url: 'neo4j://127.0.0.1:7687'
  new_user: 'neo4j'
  new_password: '23109900'

#  new_url: 'neo4j+s://99c1a702.databases.neo4j.io:7687'