neo4j:
#  url: 'neo4j://127.0.0.1:7687'
  url: 'neo4j://neo4j_user:7687'
  user: 'neo4j'
  password: '231099'
  file: 'data/2021-11-19 Roder связи.xlsx'
  last_url: 'neo4j://neo4j_historical:7687'
  new_user: 'neo4j'
  new_password: '231099'
  new_url: 'neo4j+s://99c1a702.databases.neo4j.io:7687'
#  last_url: 'neo4j://127.0.0.1:7688'